### ISSUE TITLE
Unable to Read Certain ID3tags.

### ISSUE THREAD

**Issue by DividedSE** [Zeugma440/atldotnet#34] opened 2019-05-27 12:50 UTC
## The problem

Yes, I am back again, as i mentioned previously there is some problem with atl tag features that i want to discuss. 
I am going one by one all the different tags to read by atl. and i finally stuck with one atleast for now.
According to Wiki & ID3.org
The Tag "TDRC" (recording time) consolidates TDAT (date), TIME (time), TRDA (recording dates), and TYER (year).
I saved a TDRC tag using a 3rdparty tool(value 2009-05-19T04:04:04) but atl unable to read it.
Atmost it can only the year 2009 using TYER tag.

p.s. I will post other issue in this thread one by one when previous get solved.

## Environment

* ATL Latest
* Windows 10 1809, VS2019.1.1, dotnet4.6.2, c#wpf

## Code To Reproduce Issue [ Good To Have ]

```
var track1 = new Track(FileNameBox.Text);
if (track1.AdditionalFields.ContainsKey(NameBox.Text))
TbTag.Text = track1.AdditionalFields[NameBox.Text];

```

**Comment by DividedSE** [comment] 2019-05-27 13:42
-:More ID3:- 
Unreadable:- TIT1(Grouping),
Half Readable:- UFID(Saved by Musicbrainz Picard)

**Comment by Zeugma440** [comment] 2019-05-27 14:29
Hi again !

- TDRC, TIT1 : I'm gonna take a look
- UFID : What do you mean by "Half-readable" ?
- Could you upload a sample (here or on my mailbox you previously noted) ? Sometimes the issue is not in a single specific tag, but in another part of the header that "garbles" everything after it.

**Comment by DividedSE** [comment] 2019-05-28 11:31
https://www.dropbox.com/s/mhin6s57td3p0xt/Capture.PNG?dl=0  The Problem
https://www.dropbox.com/s/0vrcxa1l56y6yi8/Testband%20-%20Copy%20-%20Copy%20-%20Copy.mp3?dl=0 The File

If u make a spreedsheet again it will great.

**Comment by Zeugma440** [comment] 2019-05-28 12:07
Thanks for the elements.

Here we go : https://docs.google.com/spreadsheets/d/104W9KSUaArXLuzUhBpbvFFGP6YGQ9HOs8lFceSkilus/edit?usp=sharing

**Comment by Zeugma440** [comment] 2019-05-30 05:29
@DividedSE 
- `TIT1` is mapped to `Track.Description`. Maybe you have missed it ?

- `UFID` : Picard respects the ID3v2.4 standard (see `UFID` in http://id3.org/id3v2.4.0-frames) : URL and identifier are separated by a `\0` byte. I'd suggest you solve the issue on your side with this piece of code. Are you OK with that or do you need a specific attribute in `Track` ?
```
string url = "";
string identifier = "";
if (track1.AdditionalFields.ContainsKey("UFID"))
{
     string[] tabS = track1.AdditionalFields["UFID"].Split('\0');
     url = tabS[0];
     if (tabS.Length > 1) identifier = tabS[1];
}
```

- `TDRC` : It happens there's currently no way of accessing the entire date through `Track` * confused *. I'm gonna add a new field to do that ?

**Comment by Zeugma440** [comment] 2019-05-30 19:58
New `Track.Date` field has been added and should solve your issue.

NB : I still have some work to do with some unit testing edge cases, but the code should be good to go for your usage.

**Comment by DividedSE** [comment] 2019-06-03 11:38
I will check it asap, as i am busy with something else. I will post more id3 in near future here. so keep this issue open.

**Comment by Zeugma440** [comment] 2019-06-03 16:03
No problem.

**Comment by Zeugma440** [comment] 2019-07-21 10:31
@DividedSE It's been two months already. Are you sure keeping this issue open is still relevant ?

**Comment by Zeugma440** [comment] 2019-09-13 07:45
Closing the issue because no news for 3 months. 
Please post another issue if you run into any other problem.

**Closed by Zeugma440** 2019-09-13 07:45 UTC
Labels: enhancement, question
